name: Merge Pull request
on:
  push:
    branches:
      - main
      - 'release-*'
      - 'hotfix-*'
  pull_request:
    types: [closed]

jobs:
  push-test:
    runs-on: ubuntu-latest
    steps:
      - name: Print job successful
        run: echo "Push branch is working"

  on_merged:
    if: github.event.pull_request.merged == true && (github.head_ref == 'main' || startsWith(github.head_ref, 'release-') || startsWith(github.head_ref, 'hotfix-'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print a message
        run: |
          echo "Pull request from branch ${{github.head_ref}} was merged!"
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions    
          git checkout dev
          git pull origin dev
          git rebase origin/$GITHUB_REF
          git push origin dev
    
      
