name: Merge Pull request
on:
  push:
    branches:
      - main
      - 'release-*'
      - 'hotfix-*'
  pull_request:
    types: [closed]

jobs:
  push-test:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout code
         uses: actions/checkout@v2
       - name: Print a message
         env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
          git fetch origin
          echo "Pull request from branch ${{github.head_ref}} was merged!"  
          git checkout dev
          git pull origin dev
          git rebase origin/${{github.head_ref}}
          git push origin dev

  on_merged:
    if: github.event.pull_request.merged == true && (github.head_ref == 'main' || startsWith(github.head_ref, 'release-') || startsWith(github.head_ref, 'hotfix-'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Print a message
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
          git fetch origin
          echo "Pull request from branch ${{github.head_ref}} was merged!"  
          git checkout dev
          git pull origin dev
          git rebase origin/${{github.head_ref}}
          git push origin dev
    
      
