name: First Workflow
on:
  push:
    branches:
      - main
      - 'release-*'
      - 'hotfix-*'
jobs:
  push-test:
    runs-on: ubuntu-latest
    steps:
      - name: Print job successful
        run: echo "Push branch is working"
    
      
