name: Merge Pull request
on:
  push:
    branches:
      - main
      - 'release-*'
      - 'hotfix-*'
  pull_request:
    types: [closed]

jobs:
  push-test:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout code
         uses: actions/checkout@v2
       - name: Dump GitHub context
         env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
         run: echo "$GITHUB_CONTEXT"
       - name: Rebase through push
         env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
          git fetch origin
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
          echo "Branch name is $BRANCH_NAME!" 
          git checkout develop
          git pull origin develop
          git rebase origin/$BRANCH_NAME
          git push origin develop

  on_merged:
    if: github.event.pull_request.merged == true && (github.head_ref == 'main' || startsWith(github.head_ref, 'release-') || startsWith(github.head_ref, 'hotfix-'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Rebase through Merge request
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
          git fetch origin
          echo "Pull request from branch ${{github.head_ref}} was merged!"  
          git checkout develop
          git pull origin develop
          git rebase origin/${{github.head_ref}}
          git push origin develop
    
      
